---
title: "Descriptive Temporal Graphs"
output: html_notebook
---

```{r message=FALSE}
library(rgdal)
library(spdep)
library(dplyr)
library(lubridate)
library(maptools)
library(rgeos)
```

Read in Spatial Point Files. 2001-10 are in one file and 11-17 are in another.

```{r}
homs_01_10 <- readOGR("~/Documents/Harvard - SM80/Thesis/Fortaleza_Hom_RGit_PRIVATE_Files/2001_10/", "hom2001a2010_final")

homs_11_17 <- readOGR("~/Documents/Harvard - SM80/Thesis/Fortaleza_Hom_RGit_PRIVATE_Files/2011_17/", "hom2011a2017_06042018" )

```

Rename columns to enable merge

YOD = Year of Death
DOD = Date of Death
HOD = Hour of Death
DOB = Date of Birth

```{r}
#Select specific columns in each
homs_01_10@data <- select(homs_01_10@data, NAME, ANO, DTOBITO, HORAOBITO, DTNASC, IDADE, SEXO, RACACOR, CAUSABAS, LINHAA, LINHAB, LINHAC, LINHAD, LINHAII, nome_novo)

homs_11_17@data <- select(homs_11_17@data, NUMERODO, ANO_OBITO, DTOBITO, HORAOBITO, DTNASC, IDADE, SEXO, RACACOR, CAUSABAS, LINHAA, LINHAB, LINHAC, LINHAD, LINHAII, BAIRRONOVO)

colnames(homs_01_10@data) <- c("possible_ID", "YOD", "DOD", "HOD", "DOB", "Age", "Sex", "Race", "Base_cause", "LineA", "LineB", "LineC", "LineD", "LineII", "Bairro")

colnames(homs_11_17@data) <- c("possible_ID", "YOD", "DOD", "HOD", "DOB", "Age", "Sex", "Race", "Base_cause", "LineA", "LineB", "LineC", "LineD", "LineII", "Bairro")

#MERGE

homs_01_17 <- do.call(rbind, list(homs_01_10, homs_11_17))
```

Detect and delete duplicates


Then get rid of duplicates
Will compare all fields except potential_ID
homs_01_17

```{r}
df <- homs_01_17@data
df$coords.x1 <- round(homs_01_17@coords[,1], 1)
df$coords.x2 <- round(homs_01_17@coords[,2], 1)

homs_01_17 <- homs_01_17[!duplicated(df),]
rm(df)
```


Creating dates

```{r}
homs_01_17$DOD = as.Date(strptime(homs_01_17$DOD, "%d%m%Y"))
homs_01_17$DOB = as.Date(strptime(homs_01_17$DOB, "%d%m%Y"))
homs_01_17$Age <- interval(homs_01_17$DOB, homs_01_17$DOD) / years(1)
```

Group ages

```{r}
homs_01_17$AgeGroup1 <- cut(homs_01_17$Age, breaks=c(0, 15, 25, 45, 65, Inf), labels=c("0-14","15-24","25-44","45-64","65+"))

homs_01_17$AgeGroup2 <- cut(homs_01_17$Age, breaks=c(0, 10, 15, 20, 25, 35, 45, 55, 75, Inf), labels=c("0-9","10-14","15-19","20-24","25-34","35-44","45-54","55-74","75+"))
```

```{r}
homs_temporal <- homs_01_17@data %>% mutate(MOD = month(DOD) + (as.integer(as.character(YOD))-2001)*12) %>% group_by(MOD) %>% summarize(count=n()) %>% na.omit()

homs_temporal$type <- "Geocoded"
```

```{r}
library(ggplot2)
ggplot() + geom_line(data=homs_temporal, aes(x=MOD, y=count))
```

```{r}
homs_total <- read_csv("~/Documents/Harvard - SM80/Thesis/Fortaleza_Hom_RGit_PRIVATE_Files/Total_homs_geo_nongeo.csv")
```

```{r}
library(tidyr)
homs_temporal_2 <- homs_total %>% select(-Total) %>% gather(MOD_name, count, January:December)
homs_temporal_2$MOD <- sapply(homs_temporal_2$MOD_name, function(x) ifelse(x=="January", 1, ifelse(x=="February", 2, ifelse(x=="March", 3, ifelse(x=="April", 4, ifelse(x=="May", 5, ifelse(x=="June", 6, ifelse(x=="July", 7, ifelse(x=="August", 8, ifelse(x=="September", 9, ifelse(x=="October", 10, ifelse(x=="November", 11, ifelse(x=="December", 12, NA)))))))))))))
homs_temporal_2$type <- "Total"
homs_temporal_2$MOD <- homs_temporal_2$MOD + (as.integer(as.character(homs_temporal_2$YOD))-2001)*12

homs_temporal <- rbind(homs_temporal, select(homs_temporal_2[homs_temporal_2$YOD != "Total", ], MOD, count, type))
rm(homs_temporal_2)
```

```{r}
homs_temporal <- rbind(homs_temporal, data.frame(MOD=1:204, count=(arrange(filter(homs_temporal, type=="Total"), MOD)$count - arrange(filter(homs_temporal, type=="Geocoded"), MOD)$count), type=rep("Missing",204)))
```

```{r}
library(ggplot2)
ggplot() + geom_line(data=homs_temporal, aes(x=MOD, y=count, group=type, color=type)) + xlab("Time") + ylab("Homicide Count") + scale_x_continuous(breaks=seq(6,204,12), labels=c(as.character(2001:2017))) + theme(axis.text.x = element_text(angle=45))
```

```{r}
homs_temporal_sex <- homs_01_17@data %>% mutate(MOD = month(DOD) + (as.integer(as.character(YOD))-2001)*12) %>% group_by(MOD, Sex) %>% summarize(count=n()) %>% na.omit() %>% filter(Sex != "I")
homs_temporal_sex$Sex <- as.character(homs_temporal_sex$Sex)
```

```{r}
library(ggplot2)
ggplot() + geom_line(data=homs_temporal_sex, aes(x=MOD, y=count, group=Sex, color=Sex)) + xlab("Time") + ylab("Homicide Count") + scale_x_continuous(breaks=seq(6,204,12), labels=c(as.character(2001:2017))) + theme(axis.text.x = element_text(angle=45))
```

```{r}
homs_days <- homs_01_17@data %>% mutate(day = weekdays(DOD)) %>% select(YOD, MOD, Sex, Bairro, AgeGroup2, day)
```

```{r}
homs_days_total <- homs_days %>% group_by(day) %>% summarize(count=n()) %>% na.omit()
homs_days_yrly <- homs_days %>% group_by(day, YOD) %>% summarize(count=n()) %>% na.omit() %>% mutate(day_yr=paste0(YOD,"_",day))
homs_days_yrly$day <- factor(homs_days_yrly$day, levels=c("Monday","Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
homs_days_agegrp <- homs_days %>% group_by(day, AgeGroup2) %>% summarize(count=n()) %>% na.omit()
homs_days_agegrp$day <- factor(homs_days_agegrp$day, levels=c("Monday","Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
homs_days_bairroyr <- homs_days %>% group_by(day, Bairro, YOD) %>% summarize(count=n()) %>% na.omit()
```

```{r}
ggplot(homs_days_total, aes(x=day, y=count)) + geom_bar(stat = "identity", fill="firebrick3") + scale_x_discrete(limits=c("Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday")) + xlab("Day of the Week") + ylab("Count")
```

```{r}
library(RColorBrewer)
ggplot(homs_days_yrly, aes(x=YOD, y=count, group=day)) + geom_bar(aes(fill=day), stat = "identity", position="dodge", size=0.1, color="black") + scale_fill_brewer(palette = "Blues") + xlab("Day of the Week by Year") + ylab("Count") 
```

```{r}

ggplot(homs_days_agegrp, aes(x=AgeGroup2, y=count, group=day)) + geom_bar(aes(fill=day), stat = "identity", position="dodge", size=0.1, color="black") + scale_fill_brewer(palette = "Blues") + xlab("Day of the Week by Age Group") + ylab("Count") 
```

```{r}
homs_days_agegrp <- homs_days_agegrp %>% group_by(AgeGroup2) %>% mutate(demean_count=count-mean(count))
ggplot(homs_days_agegrp, aes(x=AgeGroup2, y=demean_count, group=day)) + geom_bar(aes(fill=day), stat = "identity", position="dodge", size=0.1, color="black") + scale_fill_brewer(palette = "Blues") + xlab("Day of the Week by Age Group") + ylab("De-meaned Count") 
```

```{r}
homs_agegrp_yr <- homs_01_17@data %>% group_by(YOD, AgeGroup2) %>% summarize(count=n()) %>% na.omit()
ggplot(homs_agegrp_yr, aes(y=AgeGroup2, x=YOD)) + geom_tile(aes(fill=count), color="white") + theme_grey() + labs(y = "Age Group", x = "Year") + scale_fill_gradient(low = "#C6DBEF", high = "#08519C") + scale_x_discrete(expand = c(0, 0)) + scale_y_discrete(expand = c(0, 0))
```


